[package]
name = "todo-cli"
version = "0.1.0"
authors = ["Matt Santacroce <matthew.r.santacroce@gmail.com>"]
edition = "2018"

[dependencies]
ansi_term = "0.11.0"
app_dirs = "^1.2.1"
chrono = "0.4.6"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"